# Generated by Django 3.1.2 on 2021-11-30 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=50, verbose_name='заголовок вопроса')),
                ('post_text', models.TextField(verbose_name='текст вопроса')),
                ('pub_date', models.DateTimeField(verbose_name='дата публикации')),
                ('author_first_name', models.CharField(max_length=50, verbose_name='имя')),
                ('author_last_name', models.CharField(max_length=50, verbose_name='фамилия')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_first_name', models.CharField(max_length=50, verbose_name='имя')),
                ('author_last_name', models.CharField(max_length=50, verbose_name='фамилия')),
                ('comment_text', models.CharField(max_length=200, verbose_name='текст комментария')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
